export { default as Costo } from './costo/Costo'
export { default as CrecimientoSostenible } from './crecimientoSostenible/CrecimientoSostenible'
export { default as Fuerza } from './fuerza/Fuerza'
export { default as Huella } from './huella/Huella'
export { default as ModeloNegocio } from './modeloNegocio/ModeloNegocio'
export { default as Proyeccion } from './proyeccion/Proyeccion'
export { default as Somos } from './somos/Somos'
