export { default as ButtonMode } from './buttonMode/ButtonMode.component'
export { default as Humburger } from './humburger/Humburger.component'
export { default as ImageFill } from './imageFill/ImageFill.component'
export { default as LinkEcreea } from './link-ecreea/LinkEcreea.component'
export { default as Logo } from './logo/Logo.component'
export { default as Menu } from './menu/Menu.component'
export { default as TitleDegradado } from './titleDegradado/TitleDegradado.component'
