name: Deployment Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  

on:
  push:
    branches:
      - main

jobs:
  deply:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Add env api url
        run: vercel env add NEXT_PUBLIC_API_URL ${{ secrets.NEXT_PUBLIC_API_URL }}  --token=${{ secrets.VERCEL_TOKEN }}
      - name: Add env api key
        run: vercel env add API_TOKEN ${{ secrets.API_TOKEN }}  --token=${{ secrets.VERCEL_TOKEN }}
      

